{
    "Stamp (Upward Cut)": [
        "Greatsword",
        "Colossal Sword",
        "Curved Greatsword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Colossal Weapon"
    ],
    "Stamp (Sweep)": [
        "Greatsword",
        "Colossal Sword",
        "Curved Greatsword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Colossal Weapon"
    ],
    "Wild Strikes": [
        "Greatsword",
        "Curved Sword",
        "Curved Greatsword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail"
    ],
    "Lion's Claw": [
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Colossal Weapon"
    ],
    "Cragblade": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Fist",
        "Claw",
        "Colossal Weapon"
    ],
    "Kick": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Fist",
        "Claw",
        "Whip",
        "Colossal Weapon"
    ],
    "Endure": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Fist",
        "Claw",
        "Whip",
        "Colossal Weapon"
    ],
    "Ground Slam": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Fist",
        "Claw",
        "Whip",
        "Colossal Weapon"
    ],
    "Earthshaker": [
        "Colossal Sword",
        "Great Hammer",
        "Greataxe",
        "Great Spear",
        "Colossal Weapon"
    ],
    "Hoarah Loux's Earthshaker": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Fist",
        "Claw",
        "Whip",
        "Colossal Weapon"
    ],
    "War Cry": [
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Fist",
        "Claw",
        "Colossal Weapon"
    ],
    "Barbaric Roar": [
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Fist",
        "Claw",
        "Colossal Weapon"
    ],
    "Braggart's Roar": [
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Fist",
        "Claw",
        "Colossal Weapon"
    ],
    "Troll's Roar": [
        "Greatsword",
        "Colossal Sword",
        "Curved Greatsword",
        "Heavy Thrusting Sword",
        "Great Hammer",
        "Greataxe",
        "Colossal Weapon"
    ],
    "Spinning Slash": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Axe",
        "Greataxe",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper"
    ],
    "Impaling Thrust": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Spear",
        "Great Spear",
        "Halberd",
        "Claw"
    ],
    "Piercing Fang": [
        "Straight Sword",
        "Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Spear",
        "Great Spear",
        "Halberd"
    ],
    "Repeating Thrust": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Spear",
        "Great Spear",
        "Halberd"
    ],
    "Double Slash": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Halberd",
        "Reaper"
    ],
    "Sword Dance": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Axe",
        "Greataxe",
        "Spear",
        "Halberd",
        "Reaper"
    ],
    "Unsheathe": [
        "Katana"
    ],
    "Quickstep": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Fist",
        "Claw",
        "Whip",
        "Colossal Weapon"
    ],
    "Bloodhound's Step": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Fist",
        "Claw",
        "Whip",
        "Colossal Weapon"
    ],
    "Raptor of the Mists": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Fist",
        "Claw",
        "Whip",
        "Colossal Weapon"
    ],
    "Beast's Roar": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Fist",
        "Claw",
        "Whip",
        "Colossal Weapon"
    ],
    "Square Off": [
        "Straight Sword"
    ],
    "Charge Forth": [
        "Twinblade",
        "Heavy Thrusting Sword",
        "Spear",
        "Great Spear",
        "Halberd"
    ],
    "Spinning Strikes": [
        "Spear",
        "Halberd",
        "Reaper"
    ],
    "Giant Hunt": [
        "Greatsword",
        "Colossal Sword",
        "Twinblade",
        "Heavy Thrusting Sword",
        "Spear",
        "Great Spear",
        "Halberd"
    ],
    "Storm Blade": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Thrusting Sword",
        "Heavy Thrusting Sword"
    ],
    "Storm Assault": [
        "Twinblade",
        "Heavy Thrusting Sword",
        "Spear",
        "Great Spear",
        "Halberd"
    ],
    "Stormcaller": [
        "Straight Sword",
        "Greatsword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper"
    ],
    "Storm Stomp": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Fist",
        "Claw",
        "Whip",
        "Colossal Weapon"
    ],
    "Vacuum Slice": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Axe",
        "Greataxe"
    ],
    "Phantom Slash": [
        "Twinblade",
        "Spear",
        "Halberd",
        "Reaper"
    ],
    "Determination": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Fist",
        "Claw",
        "Whip",
        "Colossal Weapon"
    ],
    "Royal Knight's Resolve": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Fist",
        "Claw",
        "Whip",
        "Colossal Weapon"
    ],
    "Glintstone Pebble": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Spear",
        "Great Spear",
        "Halberd"
    ],
    "Glintblade Phalanx": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Spear",
        "Great Spear",
        "Halberd"
    ],
    "Carian Greatsword": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword"
    ],
    "Carian Grandeur": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword"
    ],
    "Spinning Weapon": [
        "Dagger",
        "Straight Sword",
        "Curved Sword",
        "Katana",
        "Twinblade",
        "Hammer",
        "Axe",
        "Flail",
        "Spear",
        "Halberd",
        "Reaper"
    ],
    "Loretta's Slash": [
        "Twinblade",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper"
    ],
    "Waves of Darkness": [
        "Colossal Sword",
        "Great Hammer",
        "Greataxe",
        "Great Spear",
        "Colossal Weapon"
    ],
    "Gravitas": [
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Colossal Weapon"
    ],
    "Flaming Strike": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Fist",
        "Claw"
    ],
    "Flame of the Redmanes": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Fist",
        "Claw",
        "Whip",
        "Colossal Weapon"
    ],
    "Eruption": [
        "Greatsword",
        "Colossal Sword",
        "Curved Greatsword",
        "Heavy Thrusting Sword",
        "Great Hammer",
        "Greataxe",
        "Colossal Weapon"
    ],
    "Prelate's Charge": [
        "Great Hammer",
        "Greataxe",
        "Colossal Weapon"
    ],
    "Black Flame Tornado": [
        "Twinblade",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper"
    ],
    "Thunderbolt": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Fist",
        "Claw",
        "Whip",
        "Colossal Weapon"
    ],
    "Lightning Slash": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Colossal Weapon"
    ],
    "Lightning Ram": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Fist",
        "Claw",
        "Whip",
        "Colossal Weapon"
    ],
    "Sacred Blade": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Fist",
        "Claw",
        "Whip",
        "Colossal Weapon"
    ],
    "Prayerful Strike": [
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Colossal Weapon"
    ],
    "Sacred Ring of Light": [
        "Spear",
        "Halberd",
        "Reaper"
    ],
    "Sacred Order": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Fist",
        "Claw",
        "Whip",
        "Colossal Weapon"
    ],
    "Shared Order": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Fist",
        "Claw",
        "Whip",
        "Colossal Weapon"
    ],
    "Golden Land": [
        "Colossal Sword",
        "Great Hammer",
        "Greataxe",
        "Great Spear",
        "Colossal Weapon"
    ],
    "Golden Slam": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Colossal Weapon"
    ],
    "Golden Vow": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Fist",
        "Claw",
        "Whip",
        "Colossal Weapon"
    ],
    "Vow of the Indomitable": [
        "Small Shield",
        "Medium Shield",
        "Greatshield"
    ],
    "Holy Ground": [
        "Small Shield",
        "Medium Shield",
        "Greatshield"
    ],
    "Poisonous Mist": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Colossal Weapon"
    ],
    "Poison Moth Flight": [
        "Dagger",
        "Straight Sword",
        "Curved Sword",
        "Katana",
        "Thrusting Sword"
    ],
    "Blood Blade": [
        "Dagger",
        "Straight Sword",
        "Curved Sword",
        "Katana",
        "Twinblade",
        "Thrusting Sword"
    ],
    "Bloody Slash": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword"
    ],
    "Blood Tax": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Spear",
        "Great Spear",
        "Halberd"
    ],
    "Ice Spear": [
        "Twinblade",
        "Spear",
        "Great Spear",
        "Halberd"
    ],
    "Chilling Mist": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Colossal Weapon"
    ],
    "Hoarfrost Stomp": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Fist",
        "Claw",
        "Whip",
        "Colossal Weapon"
    ],
    "Spectral Lance": [
        "Spear",
        "Great Spear",
        "Halberd"
    ],
    "Lifesteal Fist": [
        "Fist",
        "Claw"
    ],
    "White Shadow's Lure": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Fist",
        "Claw",
        "Whip",
        "Colossal Weapon"
    ],
    "Assassin's Gambit": [
        "Dagger",
        "Straight Sword",
        "Katana",
        "Thrusting Sword"
    ],
    "Mighty Shot": [
        "Light Bow",
        "Bow"
    ],
    "Through and Through": [
        "Greatbow"
    ],
    "Barrage": [
        "Light Bow"
    ],
    "Sky Shot": [
        "Light Bow",
        "Bow"
    ],
    "Enchanted Shot": [
        "Light Bow",
        "Bow"
    ],
    "Rain of Arrows": [
        "Light Bow",
        "Bow",
        "Greatbow"
    ],
    "Parry": [
        "Dagger",
        "Curved Sword",
        "Thrusting Sword",
        "Fist",
        "Claw",
        "Small Shield",
        "Medium Shield"
    ],
    "Golden Parry": [
        "Small Shield",
        "Medium Shield"
    ],
    "Storm Wall": [
        "Small Shield",
        "Medium Shield"
    ],
    "Shield Bash": [
        "Small Shield",
        "Medium Shield",
        "Greatshield"
    ],
    "Shield Crash": [
        "Small Shield",
        "Medium Shield",
        "Greatshield"
    ],
    "Barricade Shield": [
        "Small Shield",
        "Medium Shield",
        "Greatshield"
    ],
    "Thops's Barrier": [
        "Small Shield",
        "Medium Shield"
    ],
    "Carian Retaliation": [
        "Small Shield",
        "Medium Shield"
    ],
    "No Skill": [
        "Small Shield",
        "Medium Shield",
        "Greatshield",
        "Torch"
    ]
}