ASHES_OF_WAR = {
    "Stamp (Upward Cut)": [
        "Greatsword",
        "Colossal Sword",
        "Curved Greatsword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Colossal Weapon"
    ],
    "Stamp (Sweep)": [
        "Greatsword",
        "Colossal Sword",
        "Curved Greatsword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Colossal Weapon"
    ],
    "Wild Strikes": [
        "Greatsword",
        "Curved Sword",
        "Curved Greatsword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail"
    ],
    "Lion's Claw": [
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Colossal Weapon"
    ],
    "Cragblade": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Fist",
        "Claw",
        "Colossal Weapon",
        "Backhand Blade",
        "Beast Claw",
    ],
    "Kick": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Fist",
        "Claw",
        "Whip",
        "Colossal Weapon",
        "Thrusting Shield",
        "Hand-to-Hand Art",
        "Throwing Blade",
        "Backhand Blade",
        "Perfume Bottle",
        "Beast Claw",
    ],
    "Endure": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Fist",
        "Claw",
        "Whip",
        "Colossal Weapon",
        "Thrusting Shield",
        "Hand-to-Hand Art",
        "Throwing Blade",
        "Backhand Blade",
        "Perfume Bottle",
        "Beast Claw",
    ],
    "Ground Slam": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Fist",
        "Claw",
        "Whip",
        "Colossal Weapon",
        "Thrusting Shield",
        "Hand-to-Hand Art",
        "Throwing Blade",
        "Backhand Blade",
        "Perfume Bottle",
        "Beast Claw",
    ],
    "Earthshaker": [
        "Colossal Sword",
        "Great Hammer",
        "Greataxe",
        "Great Spear",
        "Colossal Weapon"
    ],
    "Hoarah Loux's Earthshaker": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Fist",
        "Claw",
        "Whip",
        "Colossal Weapon",
        "Thrusting Shield",
        "Hand-to-Hand Art",
        "Throwing Blade",
        "Backhand Blade",
        "Perfume Bottle",
        "Beast Claw",
    ],
    "War Cry": [
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Fist",
        "Claw",
        "Colossal Weapon",
        "Hand-to-Hand Art",
        "Beast Claw",
    ],
    "Barbaric Roar": [
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Fist",
        "Claw",
        "Colossal Weapon",
        "Hand-to-Hand Art",
        "Beast Claw",
    ],
    "Braggart's Roar": [
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Fist",
        "Claw",
        "Colossal Weapon",
        "Hand-to-Hand Art",
        "Beast Claw",
    ],
    "Troll's Roar": [
        "Greatsword",
        "Colossal Sword",
        "Curved Greatsword",
        "Heavy Thrusting Sword",
        "Great Hammer",
        "Greataxe",
        "Colossal Weapon"
    ],
    "Spinning Slash": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Axe",
        "Greataxe",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Throwing Blade",
        "Backhand Blade",
    ],
    "Impaling Thrust": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Spear",
        "Great Spear",
        "Halberd",
        "Claw",
        "Thrusting Shield",
        "Throwing Blade",
    ],
    "Piercing Fang": [
        "Straight Sword",
        "Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Spear",
        "Great Spear",
        "Halberd",
        "Thrusting Shield",
    ],
    "Repeating Thrust": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Spear",
        "Great Spear",
        "Halberd",
        "Thrusting Shield",
        "Throwing Blade",
    ],
    "Double Slash": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Halberd",
        "Reaper",
        "Throwing Blade",
    ],
    "Sword Dance": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Axe",
        "Greataxe",
        "Spear",
        "Halberd",
        "Reaper",
        "Throwing Blade",
        "Backhand Blade",
    ],
    "Unsheathe": [
        "Katana"
    ],
    "Quickstep": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Fist",
        "Claw",
        "Whip",
        "Colossal Weapon",
        "Thrusting Shield",
        "Hand-to-Hand Art",
        "Throwing Blade",
        "Backhand Blade",
        "Perfume Bottle",
        "Beast Claw",
    ],
    "Bloodhound's Step": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Fist",
        "Claw",
        "Whip",
        "Colossal Weapon",
        "Thrusting Shield",
        "Hand-to-Hand Art",
        "Throwing Blade",
        "Backhand Blade",
        "Perfume Bottle",
        "Beast Claw",
    ],
    "Raptor of the Mists": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Fist",
        "Claw",
        "Whip",
        "Colossal Weapon",
        "Thrusting Shield",
        "Hand-to-Hand Art",
        "Throwing Blade",
        "Backhand Blade",
        "Perfume Bottle",
    ],
    "Beast's Roar": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Fist",
        "Claw",
        "Whip",
        "Colossal Weapon",
        "Thrusting Shield",
        "Hand-to-Hand Art",
        "Throwing Blade",
        "Backhand Blade",
        "Perfume Bottle",
    ],
    "Square Off": [
        "Straight Sword"
    ],
    "Charge Forth": [
        "Twinblade",
        "Heavy Thrusting Sword",
        "Spear",
        "Great Spear",
        "Halberd",
        "Thrusting Shield",
    ],
    "Spinning Strikes": [
        "Spear",
        "Halberd",
        "Reaper"
    ],
    "Giant Hunt": [
        "Greatsword",
        "Colossal Sword",
        "Twinblade",
        "Heavy Thrusting Sword",
        "Spear",
        "Great Spear",
        "Halberd",
        "Thrusting Shield",
    ],
    "Storm Blade": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Throwing Blade",
    ],
    "Storm Assault": [
        "Twinblade",
        "Heavy Thrusting Sword",
        "Spear",
        "Great Spear",
        "Halberd",
        "Thrusting Shield",
    ],
    "Stormcaller": [
        "Straight Sword",
        "Greatsword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper"
    ],
    "Storm Stomp": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Fist",
        "Claw",
        "Whip",
        "Colossal Weapon",
        "Thrusting Shield",
        "Hand-to-Hand Art",
        "Throwing Blade",
        "Backhand Blade",
        "Perfume Bottle",
        "Beast Claw",
    ],
    "Vacuum Slice": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Axe",
        "Greataxe",
        "Throwing Blade",
    ],
    "Phantom Slash": [
        "Twinblade",
        "Spear",
        "Halberd",
        "Reaper"
    ],
    "Determination": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Fist",
        "Claw",
        "Whip",
        "Colossal Weapon",
        "Thrusting Shield",
        "Backhand Blade",
        "Beast Claw",
    ],
    "Royal Knight's Resolve": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Fist",
        "Claw",
        "Whip",
        "Colossal Weapon",
        "Thrusting Shield",
        "Backhand Blade",
        "Beast Claw",
    ],
    "Glintstone Pebble": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Spear",
        "Great Spear",
        "Halberd",
        "Thrusting Shield",
        "Throwing Blade",
    ],
    "Glintblade Phalanx": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Spear",
        "Great Spear",
        "Halberd",
        "Thrusting Shield",
        "Throwing Blade",
    ],
    "Carian Greatsword": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Throwing Blade",
    ],
    "Carian Grandeur": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Throwing Blade",
    ],
    "Spinning Weapon": [
        "Dagger",
        "Straight Sword",
        "Curved Sword",
        "Katana",
        "Twinblade",
        "Hammer",
        "Axe",
        "Flail",
        "Spear",
        "Halberd",
        "Reaper",
        "Thrusting Shield",
        "Throwing Blade",
        "Backhand Blade",
    ],
    "Loretta's Slash": [
        "Twinblade",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper"
    ],
    "Waves of Darkness": [
        "Colossal Sword",
        "Great Hammer",
        "Greataxe",
        "Great Spear",
        "Colossal Weapon"
    ],
    "Gravitas": [
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Colossal Weapon",
        "Thrusting Shield",
        "Backhand Blade",
    ],
    "Flaming Strike": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Fist",
        "Claw",
        "Thrusting Shield",
        "Backhand Blade",
        "Beast Claw",
    ],
    "Flame of the Redmanes": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Fist",
        "Claw",
        "Whip",
        "Colossal Weapon",
        "Thrusting Shield",
        "Hand-to-Hand Art",
        "Throwing Blade",
        "Backhand Blade",
        "Beast Claw",
    ],
    "Eruption": [
        "Greatsword",
        "Colossal Sword",
        "Curved Greatsword",
        "Heavy Thrusting Sword",
        "Great Hammer",
        "Greataxe",
        "Colossal Weapon"
    ],
    "Prelate's Charge": [
        "Great Hammer",
        "Greataxe",
        "Colossal Weapon"
    ],
    "Black Flame Tornado": [
        "Twinblade",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper"
    ],
    "Thunderbolt": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Fist",
        "Claw",
        "Whip",
        "Colossal Weapon",
        "Thrusting Shield",
        "Throwing Blade",
        "Backhand Blade",
        "Beast Claw",
    ],
    "Lightning Slash": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Colossal Weapon"
    ],
    "Lightning Ram": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Fist",
        "Claw",
        "Whip",
        "Colossal Weapon",
        "Thrusting Shield",
        "Hand-to-Hand Art",
        "Throwing Blade",
        "Backhand Blade",
        "Beast Claw",
    ],
    "Sacred Blade": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Fist",
        "Claw",
        "Whip",
        "Colossal Weapon",
        "Thrusting Shield",
    ],
    "Prayerful Strike": [
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Colossal Weapon"
    ],
    "Sacred Ring of Light": [
        "Spear",
        "Halberd",
        "Reaper"
    ],
    "Sacred Order": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Fist",
        "Claw",
        "Whip",
        "Colossal Weapon",
        "Thrusting Shield",
        "Backhand Blade",
        "Beast Claw",
    ],
    "Shared Order": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Fist",
        "Claw",
        "Whip",
        "Colossal Weapon",
        "Backhand Blade",
        "Beast Claw",
    ],
    "Golden Land": [
        "Colossal Sword",
        "Great Hammer",
        "Greataxe",
        "Great Spear",
        "Colossal Weapon",
    ],
    "Golden Slam": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Colossal Weapon",
        "Thrusting Shield",
        "Hand-to-Hand Art",
        "Throwing Blade",
        "Backhand Blade",
        "Beast Claw",
    ],
    "Golden Vow": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Fist",
        "Claw",
        "Whip",
        "Colossal Weapon",
        "Thrusting Shield",
        "Hand-to-Hand Art",
        "Throwing Blade",
        "Backhand Blade",
        "Beast Claw",
    ],
    "Vow of the Indomitable": [
        "Small Shield",
        "Medium Shield",
        "Greatshield",
        "Thrusting Shield",
    ],
    "Holy Ground": [
        "Small Shield",
        "Medium Shield",
        "Greatshield",
        "Thrusting Shield",
    ],
    "Poisonous Mist": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Colossal Weapon",
        "Thrusting Shield",
    ],
    "Poison Moth Flight": [
        "Dagger",
        "Straight Sword",
        "Curved Sword",
        "Katana",
        "Thrusting Sword",
        "Throwing Blade",
        "Backhand Blade",
    ],
    "Blood Blade": [
        "Dagger",
        "Straight Sword",
        "Curved Sword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Throwing Blade",
        "Backhand Blade",
    ],
    "Bloody Slash": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Throwing Blade",
    ],
    "Blood Tax": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Spear",
        "Great Spear",
        "Halberd",
        "Thrusting Shield",
        "Throwing Blade",
    ],
    "Ice Spear": [
        "Twinblade",
        "Spear",
        "Great Spear",
        "Halberd"
    ],
    "Chilling Mist": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Colossal Weapon",
        "Thrusting Shield",
    ],
    "Hoarfrost Stomp": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Fist",
        "Claw",
        "Whip",
        "Colossal Weapon",
        "Thrusting Shield",
        "Hand-to-Hand Art",
        "Throwing Blade",
        "Backhand Blade",
        "Beast Claw",
    ],
    "Spectral Lance": [
        "Spear",
        "Great Spear",
        "Halberd"
    ],
    "Lifesteal Fist": [
        "Fist",
        "Claw",
        "Hand-to-Hand Art",
        "Beast Claw",
    ],
    "White Shadow's Lure": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Fist",
        "Claw",
        "Whip",
        "Colossal Weapon",
        "Thrusting Shield",
        "Hand-to-Hand Art",
        "Throwing Blade",
        "Backhand Blade",
        "Beast Claw",
    ],
    "Assassin's Gambit": [
        "Dagger",
        "Straight Sword",
        "Katana",
        "Thrusting Sword",
        "Throwing Blade",
    ],
    "Mighty Shot": [
        "Light Bow",
        "Bow"
    ],
    "Through and Through": [
        "Greatbow"
    ],
    "Barrage": [
        "Light Bow"
    ],
    "Sky Shot": [
        "Light Bow",
        "Bow"
    ],
    "Enchanted Shot": [
        "Light Bow",
        "Bow"
    ],
    "Rain of Arrows": [
        "Light Bow",
        "Bow",
        "Greatbow"
    ],
    "Parry": [
        "Dagger",
        "Curved Sword",
        "Thrusting Sword",
        "Fist",
        "Claw",
        "Small Shield",
        "Medium Shield",
        "Throwing Blade",
    ],
    "Golden Parry": [
        "Small Shield",
        "Medium Shield"
    ],
    "Storm Wall": [
        "Small Shield",
        "Medium Shield"
    ],
    "Shield Bash": [
        "Small Shield",
        "Medium Shield",
        "Greatshield",
        "Thrusting Shield",
    ],
    "Shield Crash": [
        "Small Shield",
        "Medium Shield",
        "Greatshield",
        "Thrusting Shield",
    ],
    "Barricade Shield": [
        "Small Shield",
        "Medium Shield",
        "Greatshield",
        "Thrusting Shield",
    ],
    "Thops's Barrier": [
        "Small Shield",
        "Medium Shield"
    ],
    "Carian Retaliation": [
        "Small Shield",
        "Medium Shield"
    ],
    "No Skill": [
        "Small Shield",
        "Medium Shield",
        "Greatshield",
        "Torch",
        "Thrusting Shield",
    ],
    //DLC Ashes of War
    "Dryleaf Whirlwind": [
        "Hand-to-Hand Art"
    ],
    "Aspects of the Crucible Wings": [
        "Dagger",
        "Straight Sword",
        "Light Greatsword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katanas",
        "Great Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Spear",
        "Great Spear",
        "Halberd",
        "Throwing Blade",
    ],
    "Spinning Gravity Thrust": [
        "Greatsword",
        "Colossal Sword",
        "Curved Greatsword",
        "Great Katana",
        "Heavy Thrusting Sword",

    ],
    "Palm Blast": [
        "Hand-to-Hand Art",
    ],
    "Piercing Throw": [
        "Throwing Blade",
    ],
    "Scattershot Throw": [
        "Throwing Blade",
    ],
    "Wall of Sparks": [
        "Perfume Bottle",
    ],
    "Rolling Sparks": [
        "Perfume Bottle",
    ],
    "Raging Beast": [
        "Beast Claw",
    ],
    "Savage Claws": [
        "Beast Claw",
    ],
    "Blind Spot": [
        "Backhand Blade",
        "Backhand Blade",
    ],
    "Swift Slash": [
        "Backhand Blade",
    ],
    "Overhead Stance": [
        "Great Katana",
    ],
    "Wing Stance": [
        "Light Greatsword",
    ],
    "Blinkbolt": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Fist",
        "Claw",
        "Colossal Weapon",
        "Whip",
        "Beast Claw",
        "Great Katana",
        "Backhand Blade",
        "Hand-to-Hand Art",
        "Light Greatsword",
        "Thrusting Shield",
    ],
    "Flame Skewer": [
        "Straight Sword",
        "Greatsword",
        "Light Greatsword",
        "Colossal Sword",
        "Katana",
        "Great Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Spears", "Great Spear",
        "Halberd",
        "Thrusting Shield",
    ],
    "Savage Lion's Claw": [
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Colossal Weapon",
    ],
    "Divine Beast Frost Stomp": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Fist",
        "Claw",
        "Colossal Weapon",
        "Whip",
        "Beast Claw",
        "Great Katana",
        "Backhand Blade",
        "Hand-to-Hand Art",
        "Light Greatsword",
        "Thrusting Shield",
    ],
    "Flame Spear": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Light Greatsword",
        "Colossal Sword",
        "Katana, Great Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Spear",
        "Great Spear",
        "Halberd",
        "Thrusting Shield",
    ],
    "Carian Sovereignty": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Light Greatsword",
        "Great Katana",
        "Throwing Blade",
    ],
    "Shriek of Sorrow": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Fist",
        "Claw",
        "Colossal Weapon",
        "Whip",
        "Beast Claw",
        "Great Katana",
        "Backhand Blade",
        "Hand-to-Hand Art",
        "Light Greatsword",
        "Thrusting Shield",
    ],
    "Ghostflame Call": [
        "Straight Sword",
        "Light Greatsword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Great Katana",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Spear",
        "Great Spear",
        "Halberd",
    ],
    "The Poison Flower Blooms Twice": [
        "Dagger",
        "Straight Sword",
        "Greatsword",
        "Colossal Sword",
        "Curved Sword",
        "Curved Greatsword",
        "Katana",
        "Twinblade",
        "Thrusting Sword",
        "Heavy Thrusting Sword",
        "Hammer",
        "Great Hammer",
        "Axe",
        "Greataxe",
        "Flail",
        "Spear",
        "Great Spear",
        "Halberd",
        "Reaper",
        "Fist",
        "Claw",
        "Colossal Weapon",
        "Whip",
        "Beast Claw",
        "Great Katana",
        "Backhand Blade",
        "Hand-to-Hand Art",
        "Light Greatsword",
        "Thrusting Shield",
    ],
    "Igon's Drake Hunt": [
        "Greatbow",
    ],
    "Shield Strike": [
        "Small Shield",
        "Medium Shield",
        "Greatshield",
        "Thrusting Shield",
    ],
}