WEAPONS = {
    "Battle Axe": { "str": 12, "dex": 8, "infusible": true },
    "Celebrant's Cleaver": { "str": 12, "dex": 8, "infusible": true },
    "Forked Hatchet": { "str": 9, "dex": 14, "infusible": true },
    "Hand Axe": { "str": 9, "dex": 8, "infusible": true },
    "Highland Axe": { "str": 12, "dex": 9, "infusible": true },
    "Icerind Hatchet": { "str": 11, "dex": 16, "infusible": false },
    "Iron Cleaver": { "str": 15, "dex": 7, "infusible": true },
    "Jawbone Axe": { "str": 14, "dex": 8, "infusible": true },
    "Ripple Blade": { "str": 11, "dex": 11, "arc": 20, "infusible": false },
    "Rosus' Axe": { "str": 18, "dex": 10, "int": 18, "infusible": false },
    "Sacrificial Axe": { "str": 16, "dex": 10, "infusible": true },
    "Stormhawk Axe": { "str": 19, "dex": 15, "infusible": false },
    "Warped Axe": { "str": 24, "dex": 8, "infusible": true },
    "Hand Ballista": { "str": 30, "dex": 14, "infusible": false },
    "Jar Cannon": { "str": 34, "dex": 12, "infusible": false },
    "Albinauric Bow": { "str": 7, "dex": 18, "infusible": true },
    "Black Bow": { "str": 9, "dex": 20, "infusible": false },
    "Erdtree Bow": { "str": 8, "dex": 12, "fth": 14, "infusible": false },
    "Horn Bow": { "str": 10, "dex": 14, "int": 12, "infusible": true },
    "Longbow": { "str": 9, "dex": 14, "infusible": true },
    "Pulley Bow": { "str": 11, "dex": 11, "infusible": false },
    "Serpent Bow": { "str": 8, "dex": 15, "arc": 11, "infusible": false },
    "Bloodhound Claws": { "str": 10, "dex": 15, "infusible": true },
    "Hookclaws": { "str": 8, "dex": 14, "infusible": true },
    "Raptor Talons": { "str": 6, "dex": 14, "infusible": true },
    "Venomous Fang": { "str": 9, "dex": 9, "infusible": true },
    "Godslayer's Greatsword": { "str": 20, "dex": 22, "fth": 20, "infusible": false },
    "Grafted Blade Greatsword": { "str": 40, "dex": 14, "infusible": false },
    "Greatsword": { "str": 31, "dex": 12, "infusible": true },
    "Maliketh's Black Blade": { "str": 34, "dex": 12, "fth": 20, "infusible": false },
    "Royal Greatsword": { "str": 26, "dex": 18, "int": 22, "infusible": false },
    "Ruins Greatsword": { "str": 50, "dex": 16, "infusible": false },
    "Starscourge Greatsword": { "str": 38, "dex": 12, "int": 15, "infusible": false },
    "Troll Knight's Sword": { "str": 20, "dex": 14, "int": 18, "infusible": false },
    "Troll's Golden Sword": { "str": 29, "dex": 10, "infusible": true },
    "Watchdog's Greatsword": { "str": 30, "dex": 10, "infusible": true },
    "Zweihander": { "str": 19, "dex": 11, "infusible": true },
    "Axe of Godfrey": { "str": 42, "dex": 14, "infusible": false },
    "Dragon Greatclaw": { "str": 30, "dex": 14, "infusible": false },
    "Duelist Greataxe": { "str": 30, "dex": 10, "infusible": true },
    "Envoy's Greathorn": { "str": 28, "dex": 12, "fth": 24, "infusible": false },
    "Fallingstar Beast Jaw": { "str": 34, "dex": 12, "int": 20, "infusible": false },
    "Ghiza's Wheel": { "str": 28, "dex": 18, "infusible": false },
    "Giant-Crusher": { "str": 60, "infusible": true },
    "Golem's Halberd": { "str": 36, "dex": 14, "infusible": true },
    "Great Club": { "str": 35, "infusible": true },
    "Prelate's Inferno Crozier": { "str": 45, "dex": 8, "infusible": true },
    "Rotten Greataxe": { "str": 30, "dex": 10, "infusible": true },
    "Rotten Staff": { "str": 34, "dex": 8, "infusible": false },
    "Staff of the Avatar": { "str": 34, "dex": 8, "infusible": false },
    "Troll's Hammer": { "str": 28, "dex": 8, "fth": 10, "infusible": true },
    "Watchdog's Staff": { "str": 34, "dex": 10, "infusible": false },
    "Arbalest": { "str": 18, "dex": 12, "infusible": false },
    "Crepus's Black-Key Crossbow": { "str": 14, "dex": 16, "infusible": false },
    "Full Moon Crossbow": { "str": 10, "dex": 10, "int": 14, "infusible": false },
    "Heavy Crossbow": { "str": 14, "dex": 10, "infusible": false },
    "Light Crossbow": { "str": 12, "dex": 8, "infusible": false },
    "Pulley Crossbow": { "str": 16, "dex": 16, "infusible": false },
    "Soldier's Crossbow": { "str": 10, "dex": 8, "infusible": false },
    "Beastman's Cleaver": { "str": 25, "dex": 14, "infusible": true },
    "Bloodhound's Fang": { "str": 18, "dex": 17, "infusible": false },
    "Dismounter": { "str": 19, "dex": 16, "infusible": true },
    "Magma Wyrm's Scalesword": { "str": 24, "dex": 15, "fth": 18, "infusible": false },
    "Monk's Flameblade": { "str": 18, "dex": 18, "infusible": true },
    "Morgott's Cursed Sword": { "str": 14, "dex": 35, "arc": 17, "infusible": false },
    "Omen Cleaver": { "str": 19, "dex": 16, "infusible": true },
    "Onyx Lord's Greatsword": { "str": 20, "dex": 16, "int": 16, "infusible": false },
    "Zamor Curved Sword": { "str": 16, "dex": 18, "infusible": false },
    "Bandit's Curved Sword": { "str": 11, "dex": 13, "infusible": true },
    "Beastman's Curved Sword": { "str": 13, "dex": 11, "infusible": true },
    "Eclipse Shotel": { "str": 10, "dex": 25, "fth": 30, "infusible": false },
    "Falchion": { "str": 9, "dex": 13, "infusible": true },
    "Flowing Curved Sword": { "str": 9, "dex": 17, "infusible": false },
    "Grossmesser": { "str": 14, "dex": 12, "infusible": true },
    "Magma Blade": { "str": 9, "dex": 15, "fth": 16, "infusible": false },
    "Mantis Blade": { "str": 10, "dex": 12, "infusible": true },
    "Nox Flowing Sword": { "str": 8, "dex": 15, "infusible": false },
    "Scavenger's Curved Sword": { "str": 9, "dex": 14, "infusible": true },
    "Scimitar": { "str": 7, "dex": 13, "infusible": true },
    "Serpent-God's Curved Sword": { "str": 13, "dex": 9, "infusible": true },
    "Shamshir": { "str": 7, "dex": 13, "infusible": true },
    "Shotel": { "str": 9, "dex": 19, "infusible": true },
    "Wing of Astel": { "str": 7, "dex": 17, "int": 20, "infusible": false },
    "Black Knife": { "str": 8, "dex": 12, "fth": 18, "infusible": false },
    "Blade of Calling": { "str": 6, "dex": 13, "fth": 15, "infusible": false },
    "Bloodstained Dagger": { "str": 9, "dex": 12, "infusible": true },
    "Celebrant's Sickle": { "str": 6, "dex": 11, "infusible": true },
    "Cinquedea": { "str": 10, "dex": 10, "infusible": true },
    "Crystal Knife": { "str": 8, "dex": 12, "int": 9, "infusible": false },
    "Dagger": { "str": 5, "dex": 9, "infusible": true },
    "Erdsteel Dagger": { "str": 7, "dex": 12, "fth": 14, "infusible": true },
    "Glintstone Kris": { "str": 5, "dex": 12, "int": 16, "infusible": false },
    "Great Knife": { "str": 6, "dex": 12, "infusible": true },
    "Ivory Sickle": { "str": 6, "dex": 11, "int": 13, "infusible": false },
    "Misericorde": { "str": 7, "dex": 12, "infusible": true },
    "Parrying Dagger": { "str": 5, "dex": 14, "infusible": true },
    "Reduvia": { "str": 5, "dex": 13, "arc": 13, "infusible": false },
    "Scorpion's Stinger": { "str": 6, "dex": 12, "infusible": false },
    "Wakizashi": { "str": 9, "dex": 13, "infusible": true },
    "Caestus": { "str": 8, "dex": 8, "infusible": true },
    "Cipher Pata": { "fth": 30, "infusible": false },
    "Clinging Bone": { "str": 8, "dex": 22, "arc": 16, "infusible": false },
    "Grafted Dragon": { "str": 20, "dex": 14, "fth": 16, "infusible": false },
    "Iron Ball": { "str": 11, "dex": 8, "infusible": true },
    "Katar": { "str": 8, "dex": 10, "infusible": true },
    "Spiked Caestus": { "str": 8, "dex": 10, "infusible": true },
    "Star Fist": { "str": 12, "dex": 8, "infusible": true },
    "Veteran's Prosthesis": { "str": 15, "dex": 12, "infusible": false },
    "Bastard's Stars": { "str": 8, "dex": 22, "int": 22, "infusible": false },
    "Chainlink Flail": { "str": 18, "dex": 12, "infusible": true },
    "Family Heads": { "str": 8, "dex": 18, "int": 16, "infusible": false },
    "Flail": { "str": 10, "dex": 18, "infusible": true },
    "Nightrider Flail": { "str": 10, "dex": 24, "infusible": true },
    "Academy Glintstone Staff": { "str": 6, "int": 28, "infusible": false },
    "Albinauric Staff": { "str": 6, "int": 10, "arc": 12, "infusible": false },
    "Astrologer's Staff": { "str": 7, "int": 16, "infusible": false },
    "Azur's Glintstone Staff": { "str": 10, "int": 52, "infusible": false },
    "Carian Glintblade Staff": { "str": 6, "dex": 12, "int": 22, "infusible": false },
    "Carian Glintstone Staff": { "str": 6, "dex": 8, "int": 24, "infusible": false },
    "Carian Regal Scepter": { "str": 8, "dex": 10, "int": 60, "infusible": false },
    "Crystal Staff": { "str": 8, "int": 48, "infusible": false },
    "Demi-Human Queen's Staff": { "str": 6, "int": 10, "infusible": false },
    "Digger's Staff": { "str": 8, "int": 12, "infusible": false },
    "Gelmir Glintstone Staff": { "str": 6, "int": 14, "fth": 14, "infusible": false },
    "Glintstone Staff": { "str": 6, "int": 10, "infusible": false },
    "Lusat's Glintstone Staff": { "str": 10, "int": 52, "infusible": false },
    "Meteorite Staff": { "str": 6, "int": 10, "infusible": false },
    "Prince of Death's Staff": { "str": 6, "int": 18, "fth": 18, "infusible": false },
    "Rotten Crystal Staff": { "str": 8, "int": 48, "infusible": false },
    "Staff of Loss": { "str": 6, "dex": 12, "int": 14, "infusible": false },
    "Staff of the Guilty": { "str": 8, "fth": 12, "infusible": false },
    "Battle Hammer": { "str": 26, "dex": 8, "infusible": true },
    "Beastclaw Greathammer": { "str": 20, "dex": 10, "fth": 18, "infusible": false },
    "Brick Hammer": { "str": 31, "infusible": true },
    "Celebrant's Skull": { "str": 18, "dex": 12, "infusible": true },
    "Cranial Vessel Candlestand": { "str": 26, "dex": 8, "fth": 22, "infusible": false },
    "Curved Great Club": { "str": 24, "dex": 10, "infusible": true },
    "Devourer's Scepter": { "str": 24, "dex": 20, "fth": 25, "infusible": false },
    "Envoy's Long Horn": { "str": 23, "dex": 11, "fth": 18, "infusible": false },
    "Great Mace": { "str": 28, "infusible": true },
    "Great Stars": { "str": 22, "dex": 12, "infusible": true },
    "Greathorn Hammer": { "str": 22, "dex": 10, "infusible": true },
    "Large Club": { "str": 22, "infusible": true },
    "Pickaxe": { "str": 22, "dex": 10, "infusible": true },
    "Rotten Battle Hammer": { "str": 26, "dex": 8, "infusible": true },
    "Lance": { "str": 20, "dex": 14, "infusible": true },
    "Mohgwyn's Sacred Spear": { "str": 24, "dex": 14, "arc": 27, "infusible": false },
    "Serpent-Hunter": { "infusible": false },
    "Siluria's Tree": { "str": 27, "dex": 13, "fth": 20, "infusible": false },
    "Treespear": { "str": 15, "dex": 22, "fth": 18, "infusible": false },
    "Vyke's War Spear": { "str": 16, "dex": 20, "fth": 18, "infusible": false },
    "Axe of Godrick": { "str": 34, "dex": 22, "infusible": false },
    "Butchering Knife": { "str": 16, "dex": 20, "infusible": true },
    "Crescent Moon Axe": { "str": 25, "dex": 15, "infusible": true },
    "Executioner's Greataxe": { "str": 34, "dex": 8, "infusible": false },
    "Gargoyle's Black Axe": { "str": 24, "dex": 8, "fth": 22, "infusible": false },
    "Gargoyle's Great Axe": { "str": 24, "dex": 8, "infusible": true },
    "Great Omenkiller Cleaver": { "str": 23, "dex": 12, "infusible": true },
    "Greataxe": { "str": 30, "dex": 8, "infusible": true },
    "Longhaft Axe": { "str": 24, "dex": 8, "infusible": true },
    "Rusted Anchor": { "str": 26, "dex": 9, "infusible": true },
    "Winged Greathorn": { "str": 30, "dex": 20, "infusible": false },
    "Erdtree Greatbow": { "str": 20, "dex": 14, "fth": 14, "infusible": false },
    "Golem Greatbow": { "str": 24, "dex": 18, "infusible": false },
    "Greatbow": { "str": 20, "dex": 20, "infusible": true },
    "Lion Greatbow": { "str": 22, "dex": 18, "infusible": false },
    "Ant's Skull Plate": { "str": 28, "infusible": true },
    "Briar Greatshield": { "str": 21, "infusible": true },
    "Crossed-Tree Towershield": { "str": 30, "infusible": true },
    "Crucible Hornshield": { "str": 26, "infusible": false },
    "Cuckoo Greatshield": { "str": 32, "infusible": true },
    "Distinguished Greatshield": { "str": 32, "infusible": true },
    "Dragon Towershield": { "str": 30, "infusible": true },
    "Dragonclaw Shield": { "str": 28, "dex": 12, "infusible": false },
    "Eclipse Crest Greatshield": { "str": 32, "infusible": true },
    "Erdtree Greatshield": { "str": 30, "fth": 12, "infusible": false },
    "Fingerprint Stone Shield": { "str": 48, "infusible": true },
    "Gilded Greatshield": { "str": 36, "infusible": true },
    "Golden Beast Crest Shield": { "str": 24, "infusible": true },
    "Manor Towershield": { "str": 30, "infusible": true },
    "Golden Greatshield": { "str": 34, "infusible": true },
    "Haligtree Crest Greatshield": { "str": 36, "infusible": true },
    "Icon Shield": { "str": 22, "infusible": false },
    "Inverted Hawk Towershield": { "str": 30, "infusible": true },
    "Jellyfish Shield": { "str": 20, "dex": 14, "infusible": false },
    "Lordsworn's Shield": { "str": 16, "infusible": true },
    "One-Eyed Shield": { "str": 36, "infusible": false },
    "Redmane Greatshield": { "str": 30, "infusible": true },
    "Spiked Palisade Shield": { "str": 20, "infusible": true },
    "Visage Shield": { "str": 44, "infusible": false },
    "Wooden Greatshield": { "str": 14, "infusible": true },
    "Alabaster Lord's Sword": { "str": 16, "dex": 12, "int": 18, "infusible": false },
    "Banished Knight's Greatsword": { "str": 17, "dex": 9, "infusible": true },
    "Bastard Sword": { "str": 16, "dex": 10, "infusible": true },
    "Blasphemous Blade": { "str": 22, "dex": 15, "fth": 21, "infusible": false },
    "Claymore": { "str": 16, "dex": 13, "infusible": true },
    "Dark Moon Greatsword": { "str": 16, "dex": 11, "int": 38, "infusible": false },
    "Death's Poker": { "str": 15, "dex": 17, "int": 11, "infusible": false },
    "Flamberge": { "str": 15, "dex": 14, "infusible": true },
    "Forked Greatsword": { "str": 14, "dex": 16, "infusible": true },
    "Gargoyle's Blackblade": { "str": 18, "dex": 10, "fth": 22, "infusible": false },
    "Gargoyle's Greatsword": { "str": 18, "dex": 10, "infusible": true },
    "Golden Order Greatsword": { "str": 16, "dex": 21, "fth": 28, "infusible": false },
    "Helphen's Steeple": { "str": 19, "dex": 10, "int": 22, "infusible": false },
    "Inseperable Sword": { "str": 18, "dex": 18, "fth": 20, "infusible": false },
    "Iron Greatsword": { "str": 18, "dex": 10, "infusible": true },
    "Knight's Greatsword": { "str": 16, "dex": 12, "infusible": true },
    "Lordsworn's Greatsword": { "str": 16, "dex": 10, "infusible": true },
    "Marais Executioner's Sword": { "str": 24, "dex": 14, "arc": 23, "infusible": false },
    "Ordovis's Greatsword": { "str": 25, "dex": 13, "fth": 15, "infusible": false },
    "Sacred Relic Sword": { "str": 14, "dex": 24, "fth": 22, "infusible": false },
    "Sword of Milos": { "str": 15, "dex": 19, "infusible": false },
    "Banished Knight's Halberd": { "str": 17, "dex": 9, "infusible": true },
    "Commander's Standard": { "str": 24, "dex": 14, "infusible": false },
    "Dragon Halberd": { "str": 22, "dex": 10, "infusible": false },
    "Gargoyle's Black Halberd": { "str": 26, "dex": 10, "fth": 22, "infusible": false },
    "Gargoyle's Halberd": { "str": 26, "dex": 10, "infusible": true },
    "Glaive": { "str": 18, "dex": 15, "infusible": true },
    "Golden Halberd": { "str": 30, "dex": 14, "fth": 12, "infusible": false },
    "Guardian's Swordspear": { "str": 17, "dex": 16, "infusible": true },
    "Halberd": { "str": 14, "dex": 12, "infusible": true },
    "Loretta's War Sickle": { "str": 20, "dex": 15, "int": 20, "infusible": false },
    "Lucerne": { "str": 15, "dex": 12, "infusible": true },
    "Nightrider Glaive": { "str": 26, "dex": 10, "infusible": true },
    "Pest's Glaive": { "str": 13, "dex": 13, "infusible": true },
    "Ripple Crescent Halberd": { "str": 12, "dex": 12, "arc": 20, "infusible": false },
    "Vulgar Militia Saw": { "str": 15, "dex": 13, "infusible": true },
    "Vulgar Militia Shotel": { "str": 14, "dex": 16, "infusible": true },
    "Club": { "str": 10, "infusible": true },
    "Curved Club": { "str": 11, "dex": 7, "infusible": true },
    "Envoy's Horn": { "str": 10, "dex": 12, "fth": 16, "infusible": false },
    "Hammer": { "str": 14, "dex": 7, "infusible": true },
    "Mace": { "str": 12, "dex": 7, "infusible": true },
    "Marika's Hammer": { "str": 20, "dex": 12, "fth": 19, "infusible": false },
    "Monk's Flamemace": { "str": 13, "dex": 13, "infusible": true },
    "Morning Star": { "str": 12, "dex": 8, "infusible": true },
    "Nox Flowing Hammer": { "str": 17, "dex": 7, "infusible": false },
    "Ringed Finger": { "str": 15, "dex": 9, "infusible": false },
    "Scepter of the All-Knowing": { "str": 12, "dex": 18, "int": 21, "infusible": false },
    "Spiked Club": { "str": 12, "dex": 7, "infusible": true },
    "Stone Club": { "str": 16, "dex": 8, "infusible": true },
    "Varre's Bouquet": { "str": 8, "dex": 16, "arc": 24, "infusible": false },
    "Warpick": { "str": 11, "dex": 9, "infusible": true },
    "Bloody Helice": { "str": 16, "dex": 19, "arc": 17, "infusible": false },
    "Dragon King's Cragblade": { "str": 18, "dex": 37, "infusible": false },
    "Godskin Stitcher": { "str": 14, "dex": 17, "infusible": true },
    "Great Epee": { "str": 15, "dex": 16, "infusible": true },
    "Dragonscale Blade": { "str": 12, "dex": 20, "infusible": false },
    "Hand of Malenia": { "str": 16, "dex": 48, "infusible": false },
    "Meteoric Ore Blade": { "str": 15, "dex": 14, "int": 18, "infusible": false },
    "Moonveil": { "str": 12, "dex": 18, "int": 23, "infusible": false },
    "Nagakiba": { "str": 18, "dex": 22, "infusible": true },
    "Rivers of Blood": { "str": 12, "dex": 18, "arc": 20, "infusible": false },
    "Serpentbone Blade": { "str": 11, "dex": 22, "infusible": false },
    "Uchigatana": { "str": 11, "dex": 15, "infusible": true },
    "Composite Bow": { "str": 15, "dex": 15, "infusible": true },
    "Harp Bow": { "str": 9, "dex": 9, "infusible": false },
    "Misbegotten Shortbow": { "str": 16, "dex": 8, "infusible": true },
    "Red Branch Shortbow": { "str": 8, "dex": 16, "infusible": true },
    "Shortbow": { "str": 8, "dex": 10, "infusible": true },
    "Albinauric Shield": { "str": 11, "infusible": true },
    "Banished Knight's Shield": { "str": 14, "infusible": true },
    "Beast Crest Heater Shield": { "str": 10, "infusible": true },
    "Beastman's Jar Shield": { "str": 10, "infusible": true },
    "Black Leather Shield": { "str": 10, "infusible": true },
    "Blue Crest Heater Shield": { "str": 10, "infusible": true },
    "Blue-Gold Kite Shield": { "str": 12, "infusible": true },
    "Brass Shield": { "str": 16, "infusible": true },
    "Candletree Wooden Shield": { "str": 8, "infusible": true },
    "Carian Knight's Shield": { "str": 10, "dex": 10, "int": 15, "infusible": true },
    "Eclipse Crest Heater Shield": { "str": 10, "infusible": true },
    "Flame Crest Wooden Shield": { "str": 8, "infusible": true },
    "Great Turtle Shield": { "str": 14, "infusible": true },
    "Hawk Crest Wooden Shield": { "str": 8, "infusible": true },
    "Heater Shield": { "str": 10, "infusible": true },
    "Horse Crest Wooden Shield": { "str": 8, "infusible": true },
    "Inverted Hawk Heater Shield": { "str": 10, "infusible": true },
    "Kite Shield": { "str": 12, "infusible": true },
    "Large Leather Shield": { "str": 8, "infusible": true },
    "Marred Leather Shield": { "str": 8, "infusible": true },
    "Marred Wooden Shield": { "str": 8, "infusible": true },
    "Red Crest Heater Shield": { "str": 10, "infusible": true },
    "Round Shield": { "str": 8, "infusible": true },
    "Scorpion Kite Shield": { "str": 12, "infusible": true },
    "Silver Mirrorshield": { "str": 12, "dex": 10, "int": 10, "infusible": false },
    "Sun Realm Shield": { "str": 8, "infusible": true },
    "Twinbird Kite Shield": { "str": 12, "infusible": true },
    "Grave Scythe": { "str": 14, "dex": 14, "infusible": true },
    "Halo Scythe": { "str": 13, "dex": 16, "fth": 15, "infusible": false },
    "Scythe": { "str": 14, "dex": 14, "infusible": true },
    "Winged Scythe": { "str": 16, "dex": 16, "fth": 24, "infusible": false },
    "Clawmark Seal": { "str": 4, "fth": 10, "infusible": false },
    "Dragon Communion Seal": { "fth": 10, "arc": 10, "infusible": false },
    "Erdtree Seal": { "fth": 40, "infusible": false },
    "Finger Seal": { "str": 4, "fth": 10, "infusible": false },
    "Frenzied Flame Seal": { "infusible": false },
    "Giant's Seal": { "str": 4, "fth": 14, "infusible": false },
    "Godslayer's Seal": { "str": 4, "fth": 27, "infusible": false },
    "Golden Order Seal": { "int": 17, "fth": 17, "infusible": false },
    "Gravel Stone Seal": { "str": 4, "fth": 18, "infusible": false },
    "Blue-White Wooden Shield": { "str": 8, "infusible": true },
    "Buckler": { "str": 8, "dex": 13, "infusible": true },
    "Coil Shield": { "str": 10, "dex": 10, "infusible": false },
    "Gilded Iron Shield": { "str": 8, "infusible": true },
    "Ice Crest Shield": { "str": 9, "infusible": true },
    "Iron Roundshield": { "str": 8, "infusible": true },
    "Man-Serpent's Shield": { "str": 8, "infusible": true },
    "Perfumer's Shield": { "str": 8, "infusible": true },
    "Pillory Shield": { "str": 10, "infusible": true },
    "Red Thorn Roundshield": { "str": 8, "infusible": true },
    "Rickety Shield": { "str": 8, "infusible": true },
    "Rift Shield": { "str": 8, "infusible": true },
    "Riveted Wooden Shield": { "str": 8, "infusible": true },
    "Scripture Wooden Shield": { "str": 8, "infusible": true },
    "Shield of the Guilty": { "str": 8, "infusible": false },
    "Smoldering Shield": { "str": 10, "dex": 9, "fth": 12, "infusible": false },
    "Spiralhorn Shield": { "str": 8, "dex": 10, "infusible": true },
    "Bolt of Gransax": { "str": 20, "dex": 40, "infusible": false },
    "Celebrant's Rib-Rake": { "str": 8, "dex": 14, "infusible": true },
    "Clayman's Harpoon": { "str": 12, "dex": 10, "int": 12, "infusible": true },
    "Cleanrot Spear": { "str": 16, "dex": 16, "fth": 14, "infusible": false },
    "Cross-Naginata": { "str": 16, "dex": 20, "infusible": true },
    "Crystal Spear": { "str": 10, "dex": 16, "int": 16, "infusible": false },
    "Death Ritual Spear": { "str": 14, "dex": 20, "int": 18, "infusible": false },
    "Inquisitor's Girandole": { "str": 18, "dex": 15, "fth": 16, "infusible": false },
    "Iron Spear": { "str": 13, "dex": 11, "infusible": true },
    "Partisan": { "str": 15, "dex": 12, "infusible": true },
    "Pike": { "str": 20, "dex": 14, "infusible": true },
    "Rotten Crystal Spear": { "str": 10, "dex": 16, "int": 16, "infusible": false },
    "Short Spear": { "str": 10, "dex": 10, "infusible": true },
    "Spear": { "str": 12, "dex": 15, "infusible": true },
    "Spiked Spear": { "str": 14, "dex": 16, "infusible": true },
    "Torchpole": { "str": 14, "dex": 15, "infusible": false },
    "Broadsword": { "str": 10, "dex": 10, "infusible": true },
    "Cane Sword": { "str": 8, "dex": 11, "infusible": true },
    "Carian Knight's Sword": { "str": 10, "dex": 10, "int": 18, "infusible": false },
    "Coded Sword": { "fth": 20, "infusible": false },
    "Crystal Sword": { "str": 13, "dex": 10, "int": 15, "infusible": false },
    "Golden Epitaph": { "str": 12, "dex": 10, "fth": 14, "infusible": false },
    "Lazuli Glintstone Sword": { "str": 8, "dex": 9, "int": 13, "infusible": false },
    "Longsword": { "str": 10, "dex": 10, "infusible": true },
    "Lordsworn's Straight Sword": { "str": 10, "dex": 10, "infusible": true },
    "Miquellan Knight's Sword": { "str": 11, "dex": 11, "fth": 16, "infusible": false },
    "Noble's Slender Sword": { "str": 8, "dex": 11, "infusible": true },
    "Ornamental Straight Sword": { "str": 10, "dex": 14, "infusible": false },
    "Regalia of Eochaid": { "str": 12, "dex": 18, "arc": 15, "infusible": false },
    "Rotten Crystal Sword": { "str": 13, "dex": 10, "int": 15, "infusible": false },
    "Short Sword": { "str": 8, "dex": 10, "infusible": true },
    "Sword of Night and Flame": { "str": 12, "dex": 12, "int": 24, "fth": 24, "infusible": false },
    "Sword of St Trina": { "str": 10, "dex": 12, "int": 14, "infusible": false },
    "Warhawk's Talon": { "str": 10, "dex": 16, "infusible": true },
    "Weathered Straight Sword": { "str": 7, "dex": 10, "infusible": true },
    "Antspur Rapier": { "str": 10, "dex": 20, "infusible": true },
    "Cleanrot Knight's Sword": { "str": 11, "dex": 13, "infusible": true },
    "Estoc": { "str": 11, "dex": 13, "infusible": true },
    "Frozen Needle": { "str": 11, "dex": 18, "infusible": false },
    "Noble's Estoc": { "str": 9, "dex": 10, "infusible": true },
    "Rapier": { "str": 7, "dex": 12, "infusible": true },
    "Rogier's Rapier": { "str": 8, "dex": 17, "infusible": true },
    "Beast-Repellent Torch": { "str": 12, "dex": 8, "infusible": false },
    "Ghostflame Torch": { "str": 10, "dex": 10, "int": 14, "infusible": false },
    "Sentry's Torch": { "str": 15, "dex": 8, "fth": 15, "infusible": false },
    "St Trina's Torch": { "str": 10, "dex": 10, "fth": 14, "infusible": false },
    "Steel-Wire Torch": { "str": 10, "dex": 8, "infusible": false },
    "Torch": { "str": 5, "dex": 5, "infusible": false },
    "Eleonora's Poleblade": { "str": 12, "dex": 21, "arc": 19, "infusible": false },
    "Gargoyle's Black Blades": { "str": 18, "dex": 15, "fth": 22, "infusible": false },
    "Gargoyle's Twinblade": { "str": 18, "dex": 15, "infusible": true },
    "Godskin Peeler": { "str": 17, "dex": 22, "infusible": true },
    "Twinblade": { "str": 10, "dex": 18, "infusible": true },
    "Twinned Knight Swords": { "str": 16, "dex": 18, "infusible": true },
    "Giant's Red Braid": { "str": 18, "dex": 12, "fth": 21, "infusible": false },
    "Hoslow's Petal Whip": { "str": 10, "dex": 20, "infusible": true },
    "Magma Whip Candlestick": { "str": 8, "dex": 16, "fth": 18, "infusible": false },
    "Thorned Whip": { "str": 8, "dex": 16, "infusible": true },
    "Urumi": { "str": 10, "dex": 19, "infusible": true },
    "Whip": { "str": 8, "dex": 14, "infusible": true },
    // dlc weapons
    //TODO: Add the weapons to the ashes of war
    // Thrusting Shield
    "Dueling Shield": { "str": 15, "dex": 14, "infusible": false }, //true
    "Carian Thrusting Shield": { "str": 17, "dex": 13, "int": 15, "infusible": false }, //true
    // Hand2Hand
    "Dryleaf Arts": { "str": 8, "dex": 8, "infusible": false }, //true
    "Dane's Footwork": { "str": 8, "dex": 8, "infusible": false }, //true
    // throwing blade
    "Smithscript Dagger": { "str": 5, "dex": 11, "int": 11, "fth": 11, "infusible": false }, //true
    // backhand
    "Backhand Blade": { "str": 10, "dex": 13, "infusible": false }, //true
    "Smithscript Cirque": { "str": 9, "dex": 14, "int": 11, "fth": 11, "infusible": false }, //true
    "Curseblade's Cirque": { "str": 9, "dex": 22, "infusible": false },
    // perfume
    "Firespark Perfume Bottle": { "str": 3, "dex": 14, "infusible": false }, //true
    "Chilling Perfume Bottle": { "str": 3, "dex": 13, "int": 13, "infusible": false }, //true
    "Frenzyflame Perfume Bottle": { "str": 3, "dex": 10, "int": 12, "fth": 12, "infusible": false }, //true
    "Lightning Perfume Bottle": { "str": 3, "dex": 16, "fth": 14, "infusible": false }, //true
    "Deadly Poison Perfume Bottle": { "str": 3, "dex": 13, "arc": 18, "infusible": false }, //true
    //beast claw
    "Red Bear's Claw": { "str": 20, "dex": 10, "infusible": false },
    "Beast Claw(Weapon)": { "str": 13, "dex": 11, "infusible": false }, //true
    // light greatsword
    "Milady": { "str": 12, "dex": 17, "infusible": false }, //true
    "Leda's Sword": { "str": 11, "dex": 22, "fth": 19, "infusible": false },
    "Rellana's Twin Blades": { "str": 13, "dex": 16, "int": 16, "fth": 16, "infusible": false },
    // great katana
    "Great Katana": { "str": 14, "dex": 18, "infusible": false }, //true
    "Dragon-Hunter's Great Katana": { "str": 15, "dex": 20, "infusible": false },
    "Rakshasa's Great Katana": { "str": 12, "dex": 27, "infusible": false },
    // all the remaing already classified weapons
    "Forked-Tongue Hatchet": { "str": 10, "dex": 13, "int": 0, "fth": 0, "arc": 0, "infusible": false },
    "Smithscript Axe": { "str": 13, "dex": 10, "int": 11, "fth": 11, "arc": 0, "infusible": true },
    "Messmer Soldier's Axe": { "str": 14, "dex": 10, "int": 0, "fth": 0, "arc": 0, "infusible": true },
    "Death Knight's Twin Axes": { "str": 14, "dex": 12, "int": 0, "fth": 16, "arc": 0, "infusible": false },
    "Rabbath's Cannon": { "str": 28, "dex": 16, "int": 0, "fth": 0, "arc": 0, "infusible": false },
    "Ansbach's Longbow": { "str": 9, "dex": 43, "int": 0, "fth": 0, "arc": 0, "infusible": false },
    "Ancient Meteoric Ore Greatsword": { "str": 35, "dex": 10, "int": 0, "fth": 0, "arc": 19, "infusible": false },
    "Fire Knight's Greatsword": { "str": 22, "dex": 12, "int": 0, "fth": 12, "arc": 0, "infusible": true },
    "Greatsword of Radahn (Light)": { "str": 32, "dex": 24, "int": 15, "fth": 0, "arc": 0, "infusible": false },
    "Greatsword of Radahn (Lord)": { "str": 32, "dex": 24, "int": 15, "fth": 0, "arc": 0, "infusible": false },
    "Moonrithyll's Knight Sword": { "str": 20, "dex": 14, "int": 18, "fth": 0, "arc": 0, "infusible": false },
    "Bloodfiend's Arm": { "str": 28, "dex": 11, "int": 0, "fth": 0, "arc": 16, "infusible": true },
    "Anvil Hammer": { "str": 30, "dex": 10, "int": 11, "fth": 20, "arc": 0, "infusible": false },
    "Devonia's Hammer": { "str": 30, "dex": 13, "int": 0, "fth": 19, "arc": 0, "infusible": false },
    "Shadow Sunflower Blossom": { "str": 24, "dex": 8, "int": 0, "fth": 25, "arc": 0, "infusible": false },
    "Gazing Finger": { "str": 20, "dex": 8, "int": 20, "fth": 14, "arc": 0, "infusible": false },
    "Repeating Crossbow": { "str": 13, "dex": 15, "int": 0, "fth": 0, "arc": 0, "infusible": false },
    "Spread Crossbow": { "str": 11, "dex": 17, "int": 0, "fth": 0, "arc": 0, "infusible": false },
    "Horned Warrior's Greatsword": { "str": 19, "dex": 16, "int": 0, "fth": 13, "arc": 0, "infusible": false },
    "Freyja's Greatsword": { "str": 25, "dex": 14, "int": 0, "fth": 0, "arc": 0, "infusible": true },
    "Spirit Sword": { "str": 8, "dex": 16, "int": 16, "fth": 0, "arc": 0, "infusible": false },
    "Falx": { "str": 12, "dex": 15, "int": 0, "fth": 0, "arc": 0, "infusible": false },
    "Dancing Blade of Ranah": { "str": 9, "dex": 20, "int": 0, "fth": 0, "arc": 0, "infusible": false },
    "Horned Warrior's Sword": { "str": 11, "dex": 14, "int": 0, "fth": 14, "arc": 0, "infusible": false },
    "Main-gauche": { "str": 7, "dex": 15, "int": 0, "fth": 0, "arc": 0, "infusible": true },
    "Fire Knight's Shortsword": { "str": 8, "dex": 13, "int": 0, "fth": 12, "arc": 0, "infusible": true },
    "Pata": { "str": 11, "dex": 15, "int": 0, "fth": 0, "arc": 0, "infusible": true },
    "Golem Fist": { "str": 24, "dex": 8, "int": 11, "fth": 11, "arc": 0, "infusible": true },
    "Madding Hand": { "str": 8, "dex": 8, "int": 13, "fth": 20, "arc": 0, "infusible": false },
    "Thiollier's Hidden Needle": { "str": 10, "dex": 22, "int": 0, "fth": 0, "arc": 15, "infusible": false },
    "Poisoned Hand": { "str": 8, "dex": 8, "int": 0, "fth": 0, "arc": 28, "infusible": false },
    "Claws of Night": { "str": 8, "dex": 20, "int": 0, "fth": 0, "arc": 0, "infusible": false },
    "Serpent Flail": { "str": 10, "dex": 24, "int": 0, "fth": 21, "arc": 0, "infusible": false },
    "Staff of the Great Beyond": { "str": 7, "dex": 0, "int": 25, "fth": 25, "arc": 0, "infusible": false },
    "Maternal Staff": { "str": 7, "dex": 0, "int": 21, "fth": 0, "arc": 21, "infusible": false },
    "Black Steel Greathammer": { "str": 25, "dex": 11, "int": 0, "fth": 17, "arc": 0, "infusible": true },
    "Smithscript Greathammer": { "str": 20, "dex": 10, "int": 11, "fth": 11, "arc": 0, "infusible": true },
    "Bloodfiend's Sacred Spear": { "str": 22, "dex": 12, "int": 0, "fth": 0, "arc": 13, "infusible": false },
    "Messmer Soldier's Spear": { "str": 19, "dex": 16, "int": 0, "fth": 0, "arc": 0, "infusible": true },
    "Spear of the Impaler": { "str": 14, "dex": 35, "int": 0, "fth": 18, "arc": 0, "infusible": false },
    "Barbed Staff-Spear": { "str": 14, "dex": 18, "int": 0, "fth": 22, "arc": 0, "infusible": false },
    "Putrescence Cleaver": { "str": 28, "dex": 10, "int": 0, "fth": 0, "arc": 15, "infusible": false },
    "Death Knight's Longhaft Axe": { "str": 23, "dex": 10, "int": 0, "fth": 18, "arc": 0, "infusible": false },
    "Bonny Butchering Knife": { "str": 16, "dex": 20, "int": 0, "fth": 0, "arc": 0, "infusible": false },
    "Igon's Greatbow": { "str": 23, "dex": 16, "int": 0, "fth": 0, "arc": 0, "infusible": true },
    "Verdigris Greatshield": { "str": 49, "dex": 0, "int": 0, "fth": 0, "arc": 0, "infusible": false },
    "Black Steel Greatshield": { "str": 35, "dex": 0, "int": 0, "fth": 0, "arc": 0, "infusible": true },
    "Lizard Greatsword": { "str": 12, "dex": 14, "int": 0, "fth": 0, "arc": 0, "infusible": true },
    "Greatsword of Damnation": { "str": 20, "dex": 15, "int": 0, "fth": 20, "arc": 0, "infusible": false },
    "Greatsword of Solitude": { "str": 27, "dex": 13, "int": 0, "fth": 0, "arc": 0, "infusible": false },
    "Spirit Glaive": { "str": 14, "dex": 17, "int": 16, "fth": 0, "arc": 0, "infusible": false },
    "Poleblade of the Bud": { "str": 14, "dex": 22, "int": 0, "fth": 0, "arc": 20, "infusible": false },
    "Flowerstone Gavel": { "str": 14, "dex": 8, "int": 0, "fth": 0, "arc": 15, "infusible": false },
    "Queelign's Greatsword": { "str": 14, "dex": 18, "int": 0, "fth": 12, "arc": 0, "infusible": true },
    "Sword Lance": { "str": 21, "dex": 11, "int": 0, "fth": 0, "arc": 0, "infusible": true },
    "Star-Lined Sword": { "str": 10, "dex": 23, "int": 21, "fth": 0, "arc": 0, "infusible": false },
    "Sword of Night": { "str": 11, "dex": 20, "int": 0, "fth": 0, "arc": 0, "infusible": false },
    "Bone Bow": { "str": 8, "dex": 11, "int": 0, "fth": 0, "arc": 0, "infusible": false },
    "Golden Lion Shield": { "str": 11, "dex": 0, "int": 0, "fth": 0, "arc": 0, "infusible": false },
    "Serpent Crest Shield": { "str": 12, "dex": 0, "int": 0, "fth": 0, "arc": 0, "infusible": true },
    "Wolf Crest Shield": { "str": 12, "dex": 0, "int": 0, "fth": 0, "arc": 0, "infusible": true },
    "Messmer Soldier Shield": { "str": 10, "dex": 0, "int": 0, "fth": 0, "arc": 0, "infusible": true },
    "Obsidian Lamina": { "str": 12, "dex": 25, "int": 0, "fth": 0, "arc": 17, "infusible": false },
    "Dryleaf Seal": { "str": 8, "dex": 0, "int": 0, "fth": 27, "arc": 0, "infusible": false },
    "Fire Knight's Seal": { "str": 8, "dex": 0, "int": 0, "fth": 23, "arc": 0, "infusible": false },
    "Spiraltree Seal": { "str": 8, "dex": 0, "int": 0, "fth": 17, "arc": 0, "infusible": false },
    "Smithscript Shield": { "str": 10, "dex": 15, "int": 11, "fth": 11, "arc": 0, "infusible": false },
    "Shield of Night": { "str": 8, "dex": 15, "int": 0, "fth": 0, "arc": 0, "infusible": false },
    "Smithscript Spear": { "str": 9, "dex": 12, "int": 11, "fth": 11, "arc": 0, "infusible": true },
    "Swift Spear": { "str": 10, "dex": 26, "int": 0, "fth": 0, "arc": 0, "infusible": true },
    "Bloodfiend's Fork": { "str": 14, "dex": 8, "int": 0, "fth": 0, "arc": 13, "infusible": true },
    "Velvet Sword of St Trina": { "str": 10, "dex": 12, "int": 14, "fth": 0, "arc": 0, "infusible": false },
    "Stone-Sheathed Sword": { "str": 16, "dex": 8, "int": 0, "fth": 0, "arc": 0, "infusible": false },
    "Sword of Light": { "str": 14, "dex": 11, "int": 0, "fth": 24, "arc": 0, "infusible": false },
    "Sword of Darkness": { "str": 14, "dex": 11, "int": 0, "fth": 24, "arc": 0, "infusible": false },
    "Carian Sorcery Sword": { "str": 10, "dex": 19, "int": 16, "fth": 0, "arc": 0, "infusible": false },
    "Lamenting Visage": { "str": 9, "dex": 0, "int": 0, "fth": 0, "arc": 0, "infusible": false },
    "Nanaya's Torch": { "str": 10, "dex": 10, "int": 14, "fth": 16, "arc": 0, "infusible": false },
    "Black Steel Twinblade": { "str": 18, "dex": 15, "int": 0, "fth": 13, "arc": 0, "infusible": true },
    "Euporia": { "str": 16, "dex": 16, "int": 0, "fth": 24, "arc": 0, "infusible": false },
    "Tooth Whip": { "str": 10, "dex": 24, "int": 0, "fth": 0, "arc": 0, "infusible": false },

}