WEAPON_CATEGORIES = {
    "Axe": [
        "Battle Axe",
        "Celebrant's Cleaver",
        "Forked Hatchet",
        "Hand Axe",
        "Highland Axe",
        "Icerind Hatchet",
        "Iron Cleaver",
        "Jawbone Axe",
        "Ripple Blade",
        "Rosus' Axe",
        "Sacrificial Axe",
        "Stormhawk Axe",
        "Warped Axe"
    ],
    "Ballista": [
        "Hand Ballista",
        "Jar Cannon"
    ],
    "Bow": [
        "Albinauric Bow",
        "Black Bow",
        "Erdtree Bow",
        "Horn Bow",
        "Longbow",
        "Pulley Bow",
        "Serpent Bow"
    ],
    "Claw": [
        "Bloodhound Claws",
        "Hookclaws",
        "Raptor Talons",
        "Venomous Fang"
    ],
    "Colossal Sword": [
        "Godslayer's Greatsword",
        "Grafted Blade Greatsword",
        "Greatsword",
        "Maliketh's Black Blade",
        "Royal Greatsword",
        "Ruins Greatsword",
        "Starscourge Greatsword",
        "Troll Knight's Sword",
        "Troll's Golden Sword",
        "Watchdog's Greatsword",
        "Zweihander"
    ],
    "Colossal Weapon": [
        "Axe of Godfrey",
        "Dragon Greatclaw",
        "Duelist Greataxe",
        "Envoy's Greathorn",
        "Fallingstar Beast Jaw",
        "Ghiza's Wheel",
        "Giant-Crusher",
        "Golem's Halberd",
        "Great Club",
        "Prelate's Inferno Crozier",
        "Rotten Greataxe",
        "Rotten Staff",
        "Staff of the Avatar",
        "Troll's Hammer",
        "Watchdog's Staff"
    ],
    "Crossbow": [
        "Arbalest",
        "Crepus's Black-Key Crossbow",
        "Full Moon Crossbow",
        "Heavy Crossbow",
        "Light Crossbow",
        "Pulley Crossbow",
        "Soldier's Crossbow"
    ],
    "Curved Greatsword": [
        "Beastman's Cleaver",
        "Bloodhound's Fang",
        "Dismounter",
        "Magma Wyrm's Scalesword",
        "Monk's Flameblade",
        "Morgott's Cursed Sword",
        "Omen Cleaver",
        "Onyx Lord's Greatsword",
        "Zamor Curved Sword"
    ],
    "Curved Sword": [
        "Bandit's Curved Sword",
        "Beastman's Curved Sword",
        "Eclipse Shotel",
        "Falchion",
        "Flowing Curved Sword",
        "Grossmesser",
        "Magma Blade",
        "Mantis Blade",
        "Nox Flowing Sword",
        "Scavenger's Curved Sword",
        "Scimitar",
        "Serpent-God's Curved Sword",
        "Shamshir",
        "Shotel",
        "Wing of Astel"
    ],
    "Dagger": [
        "Black Knife",
        "Blade of Calling",
        "Bloodstained Dagger",
        "Celebrant's Sickle",
        "Cinquedea",
        "Crystal Knife",
        "Dagger",
        "Erdsteel Dagger",
        "Glintstone Kris",
        "Great Knife",
        "Ivory Sickle",
        "Misericorde",
        "Parrying Dagger",
        "Reduvia",
        "Scorpion's Stinger",
        "Wakizashi"
    ],
    "Fist": [
        "Caestus",
        "Cipher Pata",
        "Clinging Bone",
        "Grafted Dragon",
        "Iron Ball",
        "Katar",
        "Spiked Caestus",
        "Star Fist",
        "Veteran's Prosthesis"
    ],
    "Flail": [
        "Bastard's Stars",
        "Chainlink Flail",
        "Family Heads",
        "Flail",
        "Nightrider Flail"
    ],
    "Glintstone Staff": [
        "Academy Glintstone Staff",
        "Albinauric Staff",
        "Astrologer's Staff",
        "Azur's Glintstone Staff",
        "Carian Glintblade Staff",
        "Carian Glintstone Staff",
        "Carian Regal Scepter",
        "Crystal Staff",
        "Demi-Human Queen's Staff",
        "Digger's Staff",
        "Gelmir Glintstone Staff",
        "Glintstone Staff",
        "Lusat's Glintstone Staff",
        "Meteorite Staff",
        "Prince of Death's Staff",
        "Rotten Crystal Staff",
        "Staff of Loss",
        "Staff of the Guilty"
    ],
    "Great Hammer": [
        "Battle Hammer",
        "Beastclaw Greathammer",
        "Brick Hammer",
        "Celebrant's Skull",
        "Cranial Vessel Candlestand",
        "Curved Great Club",
        "Devourer's Scepter",
        "Envoy's Long Horn",
        "Great Mace",
        "Great Stars",
        "Greathorn Hammer",
        "Large Club",
        "Pickaxe",
        "Rotten Battle Hammer"
    ],
    "Great Spear": [
        "Lance",
        "Mohgwyn's Sacred Spear",
        "Serpent-Hunter",
        "Siluria's Tree",
        "Treespear",
        "Vyke's War Spear"
    ],
    "Greataxe": [
        "Axe of Godrick",
        "Butchering Knife",
        "Crescent Moon Axe",
        "Executioner's Greataxe",
        "Gargoyle's Black Axe",
        "Gargoyle's Great Axe",
        "Great Omenkiller Cleaver",
        "Greataxe",
        "Longhaft Axe",
        "Rusted Anchor",
        "Winged Greathorn"
    ],
    "Greatbow": [
        "Erdtree Greatbow",
        "Golem Greatbow",
        "Greatbow",
        "Lion Greatbow"
    ],
    "Greatshield": [
        "Ant's Skull Plate",
        "Briar Greatshield",
        "Crossed-Tree Towershield",
        "Crucible Hornshield",
        "Cuckoo Greatshield",
        "Distinguished Greatshield",
        "Dragon Towershield",
        "Dragonclaw Shield",
        "Eclipse Crest Greatshield",
        "Erdtree Greatshield",
        "Fingerprint Stone Shield",
        "Gilded Greatshield",
        "Golden Beast Crest Shield",
        "Golden Greatshield",
        "Haligtree Crest Greatshield",
        "Icon Shield",
        "Inverted Hawk Towershield",
        "Jellyfish Shield",
        "Lordsworn's Shield",
        "Manor Towershield",
        "One-Eyed Shield",
        "Redmane Greatshield",
        "Spiked Palisade Shield",
        "Visage Shield",
        "Wooden Greatshield"
    ],
    "Greatsword": [
        "Alabaster Lord's Sword",
        "Banished Knight's Greatsword",
        "Bastard Sword",
        "Blasphemous Blade",
        "Claymore",
        "Dark Moon Greatsword",
        "Death's Poker",
        "Flamberge",
        "Forked Greatsword",
        "Gargoyle's Blackblade",
        "Gargoyle's Greatsword",
        "Golden Order Greatsword",
        "Helphen's Steeple",
        "Inseperable Sword",
        "Iron Greatsword",
        "Knight's Greatsword",
        "Lordsworn's Greatsword",
        "Marais Executioner's Sword",
        "Ordovis's Greatsword",
        "Sacred Relic Sword",
        "Sword of Milos"
    ],
    "Halberd": [
        "Banished Knight's Halberd",
        "Commander's Standard",
        "Dragon Halberd",
        "Gargoyle's Black Halberd",
        "Gargoyle's Halberd",
        "Glaive",
        "Golden Halberd",
        "Guardian's Swordspear",
        "Halberd",
        "Loretta's War Sickle",
        "Lucerne",
        "Nightrider Glaive",
        "Pest's Glaive",
        "Ripple Crescent Halberd",
        "Vulgar Militia Saw",
        "Vulgar Militia Shotel"
    ],
    "Hammer": [
        "Club",
        "Curved Club",
        "Envoy's Horn",
        "Hammer",
        "Mace",
        "Marika's Hammer",
        "Monk's Flamemace",
        "Morning Star",
        "Nox Flowing Hammer",
        "Ringed Finger",
        "Scepter of the All-Knowing",
        "Spiked Club",
        "Stone Club",
        "Varre's Bouquet",
        "Warpick"
    ],
    "Heavy Thrusting Sword": [
        "Bloody Helice",
        "Dragon King's Cragblade",
        "Godskin Stitcher",
        "Great Epee"
    ],
    "Katana": [
        "Dragonscale Blade",
        "Hand of Malenia",
        "Meteoric Ore Blade",
        "Moonveil",
        "Nagakiba",
        "Rivers of Blood",
        "Serpentbone Blade",
        "Uchigatana"
    ],
    "Light Bow": [
        "Composite Bow",
        "Harp Bow",
        "Misbegotten Shortbow",
        "Red Branch Shortbow",
        "Shortbow"
    ],
    "Medium Shield": [
        "Albinauric Shield",
        "Banished Knight's Shield",
        "Beast Crest Heater Shield",
        "Beastman's Jar Shield",
        "Black Leather Shield",
        "Blue Crest Heater Shield",
        "Blue-Gold Kite Shield",
        "Brass Shield",
        "Candletree Wooden Shield",
        "Carian Knight's Shield",
        "Eclipse Crest Heater Shield",
        "Flame Crest Wooden Shield",
        "Great Turtle Shield",
        "Hawk Crest Wooden Shield",
        "Heater Shield",
        "Horse Crest Wooden Shield",
        "Inverted Hawk Heater Shield",
        "Kite Shield",
        "Large Leather Shield",
        "Marred Leather Shield",
        "Marred Wooden Shield",
        "Red Crest Heater Shield",
        "Round Shield",
        "Scorpion Kite Shield",
        "Silver Mirrorshield",
        "Sun Realm Shield",
        "Twinbird Kite Shield"
    ],
    "Reaper": [
        "Grave Scythe",
        "Halo Scythe",
        "Scythe",
        "Winged Scythe"
    ],
    "Sacred Seal": [
        "Clawmark Seal",
        "Dragon Communion Seal",
        "Erdtree Seal",
        "Finger Seal",
        "Frenzied Flame Seal",
        "Giant's Seal",
        "Godslayer's Seal",
        "Golden Order Seal",
        "Gravel Stone Seal"
    ],
    "Small Shield": [
        "Blue-White Wooden Shield",
        "Buckler",
        "Coil Shield",
        "Gilded Iron Shield",
        "Ice Crest Shield",
        "Iron Roundshield",
        "Man-Serpent's Shield",
        "Perfumer's Shield",
        "Pillory Shield",
        "Red Thorn Roundshield",
        "Rickety Shield",
        "Rift Shield",
        "Riveted Wooden Shield",
        "Scripture Wooden Shield",
        "Shield of the Guilty",
        "Smoldering Shield",
        "Spiralhorn Shield"
    ],
    "Spear": [
        "Bolt of Gransax",
        "Celebrant's Rib-Rake",
        "Clayman's Harpoon",
        "Cleanrot Spear",
        "Cross-Naginata",
        "Crystal Spear",
        "Death Ritual Spear",
        "Inquisitor's Girandole",
        "Iron Spear",
        "Partisan",
        "Pike",
        "Rotten Crystal Spear",
        "Short Spear",
        "Spear",
        "Spiked Spear",
        "Torchpole"
    ],
    "Straight Sword": [
        "Broadsword",
        "Cane Sword",
        "Carian Knight's Sword",
        "Coded Sword",
        "Crystal Sword",
        "Golden Epitaph",
        "Lazuli Glintstone Sword",
        "Longsword",
        "Lordsworn's Straight Sword",
        "Miquellan Knight's Sword",
        "Noble's Slender Sword",
        "Ornamental Straight Sword",
        "Regalia of Eochaid",
        "Rotten Crystal Sword",
        "Short Sword",
        "Sword of Night and Flame",
        "Sword of St Trina",
        "Warhawk's Talon",
        "Weathered Straight Sword"
    ],
    "Thrusting Sword": [
        "Antspur Rapier",
        "Cleanrot Knight's Sword",
        "Estoc",
        "Frozen Needle",
        "Noble's Estoc",
        "Rapier",
        "Rogier's Rapier"
    ],
    "Torch": [
        "Beast-Repellent Torch",
        "Ghostflame Torch",
        "Sentry's Torch",
        "St Trina's Torch",
        "Steel-Wire Torch",
        "Torch"
    ],
    "Twinblade": [
        "Eleonora's Poleblade",
        "Gargoyle's Black Blades",
        "Gargoyle's Twinblade",
        "Godskin Peeler",
        "Twinblade",
        "Twinned Knight Swords"
    ],
    "Whip": [
        "Giant's Red Braid",
        "Hoslow's Petal Whip",
        "Magma Whip Candlestick",
        "Thorned Whip",
        "Urumi",
        "Whip"
    ]
}